---
title: "Tidy Tuesday Video Games"
output: github_document
---

```{r Load Packages}
library(tidyverse)
library(lubridate)
```

```{r Download and summarise data}

video_games <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-07-30/video_games.csv")

summary(video_games)

data <- video_games %>%
  mutate(release_date = mdy(release_date))
```


```{r Calculate longest running publishers}

df <- data%>%
  select(publisher,release_date)%>%
  group_by(publisher) %>%
  summarise(max_date=max(release_date), min_date=min(release_date),counts=as.numeric(n()))%>%
  mutate(lag=as.numeric((formatC((max_date-min_date)/365,digits=2, format="f"))))%>% 
  arrange(desc(counts))
  
df<-na.omit(df) 
  
df2 <- head(df,20) 

```

```{r Scatter Diagram looking at years active}
graph <- ggplot(df2, aes(x=lag,y=counts))+
  geom_point()+
  geom_label(label=paste(df2$publisher,":",df2$counts), fill="red", color='white', check_overlap = TRUE, size=2,alpha=0.25)+
  labs(x="Years Active", y = "Number of Video Games Released",title="Does Number of Years Active Affect the Number of Video Games Released?")+
  xlim(-2,17.5)+
 theme(panel.grid.major = element_blank(),
       panel.grid.minor = element_blank(),
       panel.background = element_rect(fill = 'black'),
       plot.background = element_rect(fill = 'black'),
       axis.title.y = element_text(color ='white'),
       axis.title.x = element_text(color ='white'),
       axis.text = element_text( color = "white"),
       plot.title = element_text(colour = 'white',face="bold",size=12))
  

graph

ggsave("videogames_tidytuesday.png", dpi = "retina")
```

